### ISSUE TITLE
Weekly Sync Up

### ISSUE THREAD

**Issue by hacdias** [ipfs/in-web-browsers#74]
Hi! When is the next weekly sync up? 😄

**Comment by lidel** [comment]
Good question. So far it was more like ad-hoc bi-weekly  meeting to  [Sketch 2018 Plan/Proposal for in-web-browsers Efforts](https://github.com/ipfs/in-web-browsers/issues/63).

@flyingzumwalt @diasdavid should we create a regular meeting for sync up (weekly, bi-weekly?), or do we want to make one last ad-hoc session to finalize OKRs in spreadsheet form (with priorities and assignments) before committing to a regular schedule?

**Comment by flyingzumwalt** [comment]
Consider carving out some time in the weekly all hands call to give updates from your WG and to flag work that's happening.  

The danger with WGs is that they tend to spawn lots of meetings. The most important principle, if you don't need to meet, don't meet. Emphasize strategies that let you coordinate work asynchronously -- github issues, kanban boards, etc. For these next few weeks, go ahead and meet weekly because you're getting used to this new WG structure and there's a lot to figure out, but try to avoid making weekly meetings a habit if possible.

**Comment by olizilla** [comment]
Let's start a weekly _in-web-browsers_ & _ipfs-gui_ sync up call. We're still a new team and I think we'd benefit from it. Let's try it out, as Q1 is winding up and we need to review our progress and plan goals for Q2. I think it's a nice tradition to have while we're getting up to speed, and we can help each other learn how IPFS world works.

I propose we start this on Monday 19th of March at 1pm UTC, and repeat it at the same time each week, and review if we still need it at the end of Q2.

@hacdias @akrych @alanshaw @lidel would that work for you?

**Comment by hacdias** [comment]
@olizilla on Mondays I'm only available after 3pm due to classes :/

**Comment by olizilla** [comment]
No worries, we can do 3pm if that works better.

**Comment by hacdias** [comment]
Cool! If everyone agrees, I'm for it

**Comment by hacdias** [comment]
@olizilla I'll probably arrive a bit late (max. 15 mins).

**Comment by flyingzumwalt** [comment]
Do you want me to add a recurring weekly entry on the IPFS community calendar at 15:00 UTC?

**Comment by alanshaw** [comment]
That time is good for me

**Comment by akrych** [comment]
That time is good for me too :) 👍

**Comment by hacdias** [comment]
@olizilla @lidel can any of you post the link here tomorrow please? 😄

**Comment by diasdavid** [comment]
@hacdias brings a good point, the cal event doesn't have a zoom url:

<img width="288" alt="image" src="https://user-images.githubusercontent.com/1211152/37577520-d755872e-2aef-11e8-8b6b-f56ec7d57281.png">


Also, feel free to take inspiration from the js-ipfs weekly dev sync up -- https://github.com/ipfs/pm/blob/master/templates/JS-IPFS-CORE-WEEKLY.md.

**Comment by diasdavid** [comment]
Just added one: 
<img width="294" alt="image" src="https://user-images.githubusercontent.com/1211152/37577676-cc2ecbca-2af0-11e8-956b-fbecf185f1c4.png"> and added as hosts @lidel's account + the two ops+zoom accounts so that anyone with login to those can record

<img width="669" alt="image" src="https://user-images.githubusercontent.com/1211152/37577698-e859a310-2af0-11e8-9495-abc40afe2c19.png">

**Comment by lidel** [comment]
PSA: we were blocking @diasdavid by using his account for these calls, so I've created a new link:
Join URL: https://protocol.zoom.us/j/791746761

**Comment by lidel** [comment]
@diasdavid are you able to edit Community calendar? We need to update the link to [this](https://protocol.zoom.us/j/791746761) + move the meeting 1 hour earlier. 
It was moved for most of us due to daylight saving time change, ale we prefer the old time:

> 
![qmsmp4k2jxvnjflbkmxbbrdnsyuuw8ffbw1jck26tppm2w](https://user-images.githubusercontent.com/157609/37898406-04d89f16-30e9-11e8-8b00-a444bfba1a84.png)

**Comment by diasdavid** [comment]
Updated the cal event with the new Zoom url
<img width="295" alt="image" src="https://user-images.githubusercontent.com/1211152/37922583-c3f1f4cc-30e1-11e8-8b93-42190d9cf9e5.png">

@lidel please confirm the time change request and I'll make it happen :)

**Comment by lidel** [comment]
@diasdavid yes, please change the time, I confirmed with @kyledrake  that works for him for now.
We can always revisit it in  future when WG membership changes.

FYI we will be defaulting to IRC (as it seem to work better for our WG) and the Zoom will be used  if we decide we really need it (eg. today to bootstrap OKR draft)

To set proper expectations within community, please :

- [ ] rename meeting in Google Calendar to "Web Browser Working Group Weekly IRC Sync"
- [ ] prepend/replace description's zoom link with IRC, eg. https://webchat.freenode.net/?channels=ipfs-in-web-browsers

Thanks!

**Comment by lidel** [comment]
It looks like both 2pm and 3pm UTC works for people who filled the doodle, so I propose we leave it as-is (at 3pm UTC) to remove step of updating community calendar ;)

**Comment by lidel** [comment]
In Q3 we will try to improve the formula of weekly sync. 

Each week will have dedicated issue with Agenda hackpad ready days before sync.

That way people can:
- get more value from watching this repo 
- write updates beforehand and just answer questions during sync 
- add agenda items before meeting

Continued in: https://github.com/ipfs/in-web-browsers/issues/88#issue-339078143
