### ISSUE TITLE
Work around gateway's trailing-slash redirects

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#8]
## Background

@gozala (2017-02-01):
> IPFS node automatically redirects if path is for the directory but without / at the end. As a side effect following redirect happens:
>
fs://ipfs/${cid}/dir -> localhost:8080/ipfs/${cid_v1_base16}/dir/
> While it would make more sense to either redirect as 
>
> fs://ipfs/${cid}/dir -> ipfs://${cid_v1_base16}/dir/
>
> or redirect and 404 here
>
> fs://ipfs/${cid}/dir -> ipfs://${cid_v1_base16}/dir
>
> Obviously former would be more preferable, but somewhat unclear how to do that given that protocol handler has no knowledge of what’s actually under the requested URL

**Comment by lgierth** [comment]
Example: https://ipfs.io/ipns/ipfs.io redirects to https://ipfs.io/ipns/ipfs.io/ -- this also breaks the "fake fs: path" in the address bar with the firefox addon.

We need this behaviour so that relative links in e.g. HTML documents always work.

One way around this is issue to set a special header in gateway requests from browser addons, and adjust the redirects in the gateway accordingly:

```
GET /ipns/ipfs.io HTTP/1.1
X-Redirect-Proto: dweb:

HTTP/1.1 301 Moved Permanently
Location: dweb:/ipns/ipfs.io/
```

**Comment by lidel** [comment]
Continued in: https://github.com/ipfs/in-web-browsers/issues/147
